# Site settings
title: Nebula Biotech
email: bensima@gmail.com
description: Nebula Biotech
baseurl: "nebulabiotech.github.io"
url: "nebulabiotech.github.io"
twitter_username: bensima
github_username:  bensima

# Build settings
markdown: kramdown
permalink: pretty
