# Site settings
title: Nebula Bio
email: bensima@gmail.com
description: Open Source Biotech
url: "www.nebula.bio"
twitter_username: bensima
github_username:  bensima

# Build settings
markdown: kramdown
permalink: pretty
