# Site settings
title: Nebula Biotech
email: bensima@gmail.com
description: Nebula Biotech
baseurl: "http://www.nebulabiotech.com"
url: "http://www.nebulabiotech.com"
twitter_username: bensima
github_username:  bensima

# Build settings
markdown: kramdown
permalink: pretty
