# Site settings
title: Nebula Biotech
email: bensima@gmail.com
description: Nebula Biotech
url: "www.nebulabiotech.com"
twitter_username: bensima
github_username:  bensima

# Build settings
markdown: kramdown
permalink: pretty
